site_name: SciCode Benchmark
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    # logo: assets/swe-agent.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: deep orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Overview: 
    - "SciCode": index.md
    - "Example problem": example_problem.md
    - "FAQ": faq.md
    - "Problem list": problems.md
  - Leaderboard: leaderboard.md
  - Preprint: "https://raw.githubusercontent.com/scicode-bench/scicode-bench.github.io/main/SciCode.pdf"
plugins:
   - glightbox
   - search
   - include-markdown
repo_url: https://github.com/scicode-bench/SciCode
repo_name: scicode-bench/SciCode
